import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'package:sqflite_common_ffi_web/sqflite_ffi_web.dart';
import 'package:flutter/foundation.dart';

class WorkoutEntry {
  final int? id; // Auto-generated by SQLite
  final DateTime date; // Calendar day in Flutter DateTime format
  final String description; // Workout description as String
  final int duration; // Duration in integer seconds

  WorkoutEntry({
    this.id,
    required this.date,
    required this.description,
    required this.duration,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'date': date.toIso8601String(),
      'description': description,
      'duration': duration,
    };
  }

  factory WorkoutEntry.fromMap(Map<String, dynamic> map) {
    return WorkoutEntry(
      id: map['id'],
      date: DateTime.parse(map['date']),
      description: map['description'],
      duration: map['duration'],
    );
  }

  static const String dbSchema = '''
      CREATE TABLE workouts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        date TEXT NOT NULL,
        description TEXT NOT NULL,
        duration INTEGER NOT NULL
      )
    ''';
}

class CalorieEntry {
  final int? id; // Auto-generated by SQLite
  final DateTime date; // Calendar day in Flutter DateTime format
  final int total; // Total calories as an integer

  CalorieEntry({this.id, required this.date, required this.total});

  Map<String, dynamic> toMap() {
    return {'id': id, 'date': date.toIso8601String(), 'total': total};
  }

  factory CalorieEntry.fromMap(Map<String, dynamic> map) {
    return CalorieEntry(
      id: map['id'],
      date: DateTime.parse(map['date']),
      total: map['total'],
    );
  }

  static const String dbSchema = '''
      CREATE TABLE calories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        date TEXT NOT NULL,
        total INTEGER NOT NULL
      )
    ''';
}

class DBHelper {
  DBHelper._privateConstructor();
  static final DBHelper instance = DBHelper._privateConstructor();

  static Database? _database;

  Future<Database> get database async {
    if (_database != null) return _database!;
    _database = await _initializeDatabase();
    return _database!;
  }

  Future<Database> _initializeDatabase() async {
    String path = join(await getDatabasesPath(), 'fitnessapp_db2.db');
    if (kIsWeb) {
      // Change default factory on the web
      databaseFactory = databaseFactoryFfiWeb;
      path = 'fitnessapp_db2_web.db';
    }
    return await openDatabase(path, version: 1, onCreate: _createTable);
  }

  Future<void> _createTable(Database db, int version) async {
    await db.execute('''
      CREATE TABLE workouts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        date TEXT NOT NULL,
        description TEXT NOT NULL,
        duration INTEGER NOT NULL
      )
    ''');
    await db.execute('''
      CREATE TABLE calories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        date TEXT NOT NULL,
        total INTEGER NOT NULL
      )
    ''');
  }

  Future<int> insertWorkout(WorkoutEntry entry) async {
    final db = await database;
    return await db.insert('workouts', entry.toMap());
  }

  Future<int> insertCalories(CalorieEntry entry) async {
    final db = await database;
    return await db.insert('calories', entry.toMap());
  }

  Future<List<WorkoutEntry>> getWorkouts() async {
    final db = await database;
    final List<Map<String, dynamic>> maps = await db.query('workouts');
    return List.generate(maps.length, (i) => WorkoutEntry.fromMap(maps[i]));
  }

  Future<List<CalorieEntry>> getCalories() async {
    final db = await database;
    final List<Map<String, dynamic>> maps = await db.query('calories');
    return List.generate(maps.length, (i) => CalorieEntry.fromMap(maps[i]));
  }

  Future<int> updateWorkout(WorkoutEntry entry) async {
    final db = await database;
    return await db.update(
      'workouts',
      entry.toMap(),
      where: 'id = ?',
      whereArgs: [entry.id],
    );
  }

  Future<int> updateCalories(CalorieEntry entry) async {
    final db = await database;
    return await db.update(
      'calories',
      entry.toMap(),
      where: 'id = ?',
      whereArgs: [entry.id],
    );
  }

  Future<int> deleteWorkout(int id) async {
    final db = await database;
    return await db.delete('workouts', where: 'id = ?', whereArgs: [id]);
  }

  Future<int> deleteCalories(int id) async {
    final db = await database;
    return await db.delete('calories', where: 'id = ?', whereArgs: [id]);
  }
}
